-- Add SMTP settings to profiles table
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS smtp_host TEXT,
ADD COLUMN IF NOT EXISTS smtp_port INTEGER,
ADD COLUMN IF NOT EXISTS smtp_user TEXT,
ADD COLUMN IF NOT EXISTS smtp_pass TEXT,
ADD COLUMN IF NOT EXISTS smtp_from TEXT,
ADD COLUMN IF NOT EXISTS use_custom_smtp BOOLEAN DEFAULT FALSE;
